### ISSUE TITLE
\pixii is never defined but used

### ISSUE THREAD

**Issue by fabian-s** [slds-lmu/latex-math#11]
https://github.com/compstat-lmu/latex-math/blob/e6a3ed5093c3c2d4e54a1d308b21cfbad7997b5e/basic-ml.tex#L129

@berndbischl : git blame says this is yours  (https://github.com/compstat-lmu/latex-math/commit/8512ddc33cbf63d4ae52fd45656d4c353ed9ab19)

**Comment by jemus42** [comment]
Checked again across all lectures, only finding hits in `latex-math` itself aside from these two uses of `\Lpixyit`. 

```
❯ rg --no-ignore -F "\Lpixyi"
lecture_i2ml/exercises/ml-basics/ex_rnw/sol_ml_basics.Rnw
20:  log-likelihood as our loss function: $$\Lpixyit = - \left(\yi \log \left(

lecture_i2ml/slides/supervised-classification/slides-classification-logistic.tex
32:$$ \argmin_{\thetab \in \Theta} \risket = \argmin_{\thetab \in \Theta} \sumin \Lpixyit.$$
```

I'd close this unless someone wants to a) Use the unused thing to make it useful or b) Remove the unused thing to keep latex-math clean.
