### ISSUE TITLE
\ll of basic-ml overwrites the "much smaller than" math operator

### ISSUE THREAD

**Issue by schalkdaniel** [slds-lmu/latex-math#12]
In `basic-ml` the `\ll` (much smaller than) command is redefined with `\ell`:
https://github.com/compstat-lmu/latex-math/blob/e4812cbfa92b1e0f36c8eb60ec81171e766f3154/basic-ml.tex#L155
Maybe remove it? I think in general it's not good to overwrite "basic math operator" ...

**Comment by davidruegamer** [comment]
:+1: had to do remove it manually now already in two other projects.

**Comment by schalkdaniel** [comment]
@berndbischl seems to be an issue ...

**Comment by schalkdaniel** [comment]
btw, here is the command to resolve it:
```
\renewcommand{\ll}{\mathchar"321C}
```

**Comment by lisa-wm** [comment]
was solved some time ago
