### ISSUE TITLE
Redefine transpose symbol

### ISSUE THREAD

**Issue by schalkdaniel** [slds-lmu/latex-math#14]
I am no fan of using `^T` as transpose symbol, it does not look that nice (in my opinion) and may confuse others if someone uses T, let's say as a counter, and wants to use `a^T`. And isn't it the same thing as using `\prime` over `'`? There are many discussions about it (e.g. [here](https://tex.stackexchange.com/questions/30619/what-is-the-best-symbol-for-vector-matrix-transpose#:~:text=The%20symbol%20%5Cintercal%20is%20quite,to%20the%20current%20math%20style.)) where they suggest nicer symbols like:
```
\newcommand*{\tran}{{\mkern-1.5mu\mathsf{T}}}
```
Here is an example for `$X^T vs. X^\tran$`:
![Screenshot from 2021-03-02 09-44-08](https://user-images.githubusercontent.com/20367117/109621996-e8907400-7b3b-11eb-9fa6-dbda01c2a9cd.png)

**Comment by lisa-wm** [comment]
fixed that, has been bugging me forever
